FROM continuumio/miniconda3

# install python 3.8.5
RUN conda install python=3.8.5

RUN echo '\
   Acquire::Retries "100";\
   Acquire::https::Timeout "240";\
   Acquire::http::Timeout "240";\
   APT::Get::Assume-Yes "true";\
   APT::Install-Recommends "false";\
   APT::Install-Suggests "false";\
   Debug::Acquire::https "true";\
   ' > /etc/apt/apt.conf.d/99custom

# install mujoco
RUN apt-get update
RUN apt-get install build-essential --yes
RUN cd /root \
    && mkdir .mujoco \
    && wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz \
    && tar -xf mujoco210-linux-x86_64.tar.gz -C .mujoco \
    && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mujoco210/bin


# install mujoco_py & safety gym
RUN apt-get install -y \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libosmesa6-dev \
    software-properties-common \
    patchelf
RUN pip install onnxruntime free-mujoco-py

RUN mkdir -p /usr/home/workspace/safety-gym
COPY safety-gym /usr/home/workspace/safety-gym
RUN cd /usr/home/workspace/safety-gym \
    && pip install -e .

# install torch with cuda support
RUN pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113 \
    && pip install install tensorflow \
    && pip install wandb moviepy opencv-python

# additional pip deps
## install mpi4py
RUN apt-get install libopenmpi-dev
RUN pip install mpi4py
RUN pip install matplotlib

WORKDIR /usr/home/workspace

# install safety gym
#CMD cd /usr/home/workspace/safety-gym && pip install -e .
