mpc_config:
    horizon: 8 # how long of the horizon to predict
    gamma: 0.98              # reward discount coefficient
    RANDOM: # TODO: warning may contain not finished modification     
        popsize: 5000            # how many random samples for mpc
    CEM:
        popsize: 500               # how many random samples for mpc
        # particle: 1                # number of particles to enlarge
        max_iters: 8
        num_elites: 12
        epsilon: 0.01 # for 0.003, it will has +- 0.05 error rate with 0.05 prob when converges
        alpha: 0.1 # weights for previous mean and var
        init_mean: 0
        init_var: 1
    RCE:
        popsize: 500               # how many random samples for mpc
        max_iters: 8
        num_elites: 12
        minimal_elites: 5                 # threshold for minimal elites
        epsilon: 0.01 # for 0.003, it will has +- 0.05 error rate with 0.05 prob when converges
        alpha: 0.1 # weights for previous mean and var
        init_mean: 0
        init_var: 1